name: rick_and_morty
description: "Rick and Morty characters list app with favorites and offline support."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

  # Networking
  graphql_flutter: ^5.2.1

  # Local storage
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.4

  # Localization
  flutter_localizations:
    sdk: flutter
  slang: ^4.12.1
  slang_flutter: ^4.12.1

  # Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

  # Navigation
  go_router: ^17.1.0

  # Other
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.1.1
  riverpod_generator: ^4.0.3
  slang_build_runner: ^4.12.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  drift_dev: ^2.31.0

flutter:
  uses-material-design: true
